version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgres: